'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TugasKelompokVB.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1kooza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1kooza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2corteo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2corteo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _3thebeatles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3thebeatles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _4mj() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4mj", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5ka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5ka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _6alegria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6alegria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7o() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7o", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alegria1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alegria1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alegria2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alegria2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property alegria3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alegria3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Alegriatrailer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Alegriatrailer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beatles1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beatles1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beatles2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beatles2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property beatles3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("beatles3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property beatlestrailer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("beatlestrailer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property captcha() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("captcha", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corteo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corteo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corteo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corteo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corteo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corteo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Corteotrailer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Corteotrailer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KA1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KA1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KA2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KA2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KA3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KA3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property KAtrailer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("KAtrailer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kooza1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kooza1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kooza2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kooza2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kooza3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kooza3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property KOOZAtrailer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("KOOZAtrailer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MJ1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MJ1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MJ2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MJ2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MJ3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MJ3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property MJtrailer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MJtrailer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property O1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("O1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property O2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("O2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property O3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("O3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Otrailer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Otrailer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gravity  defied,   enemies confronted,   noble  combat   becomes 
        '''acrobatic.
        '''
        '''War   has  never  been  fought  this  way. A  colossal, moving stage 
        '''is the battlefield. Up is down, land becomes sky. These dimension-
        '''bending confrontations redefine what it means to fight.
        '''
        '''Bodies  full of   strength,  glowing with light and heat. Minds  as bright 
        '''and clear as the vast heavens, the great ocean, and the highest peak.
        '''
        '''Determination is the path, victory the reward..
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A  wheel of   death,   a lock-up  for 
        '''the  faint-of-heart.   Part prison, all 
        '''terrifying   machine,   this   infernal 
        '''contraption  tests a  warrior’s  true 
        '''courage..
        '''</summary>
        Friend ReadOnly Property String10() As String
            Get
                Return ResourceManager.GetString("String10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Iconic  Choreography  Reflective  of 
        '''Michael’s fascination with gangster 
        '''films,   themes,   and   characters, 
        '''“Smooth Criminal” features Yakuza-
        '''inspired characters in fedoras and 
        '''pinstriped suits..
        '''</summary>
        Friend ReadOnly Property String11() As String
            Get
                Return ResourceManager.GetString("String11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Legendary Beats Mythical music that 
        '''remains as poignant and relevant today 
        '''as when it first took audiences by storm..
        '''</summary>
        Friend ReadOnly Property String12() As String
            Get
                Return ResourceManager.GetString("String12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Super. Sonic. Each of the theatre’s 
        '''1,804 seats has three speakers – left, 
        '''right and center – for a total of 5,412 
        '''seat speakers..
        '''</summary>
        Friend ReadOnly Property String13() As String
            Get
                Return ResourceManager.GetString("String13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Strawberry Fields Forever 
        '''
        '''A new dimension of strangeness 
        '''and magic..
        '''</summary>
        Friend ReadOnly Property String14() As String
            Get
                Return ResourceManager.GetString("String14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All You Need is Love A montage of 
        '''The Beatles  projected on  curtains 
        '''that fill the audience with wonderful 
        '''nostalgia and a message of LOVE..
        '''</summary>
        Friend ReadOnly Property String15() As String
            Get
                Return ResourceManager.GetString("String15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to YESTERDAY 
        '''
        '''Reminiscent melancholy rooted in the 
        '''love that once was and the longing for 
        '''what could be, a trapeze duet floating 
        '''through the lyrics of Paul McCartney as 
        '''his presence serenades from above..
        '''</summary>
        Friend ReadOnly Property String16() As String
            Get
                Return ResourceManager.GetString("String16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skeleton Dance A crazy
        '''choreographed trip to the dark side..
        '''</summary>
        Friend ReadOnly Property String17() As String
            Get
                Return ResourceManager.GetString("String17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wheel of Death 
        '''
        '''The crowd holds its collective breath.
        '''Can the astonishingly brave performers 
        '''somehow tame the enormous spinning 
        '''contraption?.
        '''</summary>
        Friend ReadOnly Property String18() As String
            Get
                Return ResourceManager.GetString("String18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Double Highwire Twin 
        '''highwires criss-cross diagonally at 15 
        '''and 25 feet above the stage..
        '''</summary>
        Friend ReadOnly Property String19() As String
            Get
                Return ResourceManager.GetString("String19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Immersive Journey
        '''
        '''Hailed by Rolling Stone as “A virtual parade of ‘wow’ moments,” 
        '''Michael Jackson ONE is an electrifying fusion of acrobatics, dance 
        '''and visuals immersing the audience into the world of Michael&apos;s music. 
        '''Driven by his biggest hits heard like never before in a riveting, 
        '''state-of-the-art surround-sound environment Michael 
        '''Jackson ONE..
        '''</summary>
        Friend ReadOnly Property String2() As String
            Get
                Return ResourceManager.GetString("String2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Love’s majestic highs Bella! Bella! 
        '''The lovers of dead clown Mauro 
        '''gather to reminisce on a life jubilantly 
        '''lived. Lithe bodies channel bittersweet 
        '''memories as they dance suspended 
        '''from a grandiose chandelier..
        '''</summary>
        Friend ReadOnly Property String20() As String
            Get
                Return ResourceManager.GetString("String20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A bed that puts some bounce into 
        '''life A cheery renaissance of our 
        '''departed hero’s exuberance and zest. 
        '''His fellow travelers gambol and cavort 
        '''on outsized beds in celebration of the 
        '''mischievous prankster’s gleeful past..
        '''</summary>
        Friend ReadOnly Property String21() As String
            Get
                Return ResourceManager.GetString("String21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Horizontal bar meets straight-up genius 
        '''A fitting farewell for Mauro, a jubilant 
        '''pageant of stunning coordination and 
        '''grandiose strength. This is how to say 
        '''goodbye to life with bravura..
        '''</summary>
        Friend ReadOnly Property String22() As String
            Get
                Return ResourceManager.GetString("String22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bateau 
        '''
        '''A ghostly ship emerges from the mist. 
        '''Flyers and catchers display incredible 
        '''timing..
        '''</summary>
        Friend ReadOnly Property String23() As String
            Get
                Return ResourceManager.GetString("String23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fire 
        '''
        '''The rage of fire and the purification 
        '''of water are blended into one – and 
        '''then displayed in this brilliantly visual 
        '''act..
        '''</summary>
        Friend ReadOnly Property String24() As String
            Get
                Return ResourceManager.GetString("String24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Underwater 
        '''
        '''All of the 150 technicians and 80 cast 
        '''members have scuba certification; 14   
        '''technicians  work   underwater  during 
        '''every performance..
        '''</summary>
        Friend ReadOnly Property String25() As String
            Get
                Return ResourceManager.GetString("String25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLAYGROUND 
        '''
        '''A hockey game on the pond turns 
        '''into a high-octane romp on ramps 
        '''where extreme skaters do crazy 
        '''flips, twists and jumps at breakneck 
        '''speed, until the ice turns into a 
        '''giant pinball machine..
        '''</summary>
        Friend ReadOnly Property String26() As String
            Get
                Return ResourceManager.GetString("String26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BALLROOM 
        '''
        '''The couple performs a spellbinding 
        '''aerial straps/skating pas de deux 
        '''that blurs the boundary between ice 
        '''and sky..
        '''</summary>
        Friend ReadOnly Property String27() As String
            Get
                Return ResourceManager.GetString("String27", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TEMPÊTE 
        '''
        '''Acrobatics and skating collide in this 
        '''high-energy number where the 
        '''vocabulary of banquine, hand-to-hand 
        '''and tumbling is intricately interwoven 
        '''with jumps, flips, spins and gliding on 
        '''blades..
        '''</summary>
        Friend ReadOnly Property String28() As String
            Get
                Return ResourceManager.GetString("String28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BRIGHTER. BOLDER. BIGGER!
        '''
        '''New acts,  costumes, choreography,  technology  and music  bring a 
        '''more vibrant and engaging experience to one of the most celebrated 
        '''shows in the world. The three-time Grammy Award winning LOVE is 
        '''a Rock &apos;n&apos; Roll poem, inspired by the poetry of the lyrics and brought 
        '''to life by a cast of world-class aerialists, acrobats and dancers. Music 
        '''Director Giles Martin, son of the legendary Beatles producer, Sir George, 
        '''has heightened LOVE’s listening experience with a compl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String3() As String
            Get
                Return ResourceManager.GetString("String3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Traditional Circus Homage
        '''
        '''A return to our origins, KOOZA combines acrobatic performance and 
        '''the art of clowning, while exploring fear, identity, recognition and power. 
        '''The Innocent&apos;s journey brings him into contact with comic characters 
        '''from  an  electrifying  world full  of surprises, thrills,  audacity  and  total 
        '''involvement..
        '''</summary>
        Friend ReadOnly Property String4() As String
            Get
                Return ResourceManager.GetString("String4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Get carried away with life
        '''
        '''The clown Mauro has passed, but his spirit is still with us. Instead of 
        '''mourning, the funeral cortege celebrates the here and hereafter with 
        '''laughter and exuberance. Rich, extravagant memories frolic with the 
        '''senses.  The  sound  of  laughter  peals around the  stage, visions of 
        '''joyous tumblers and players fascinate the eyes. Regret and melancholy 
        '''retreat in the face of a cavalcade of lively recollections of a life gloriously
        '''lived. A festive parade that entertains;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String5() As String
            Get
                Return ResourceManager.GetString("String5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Experience an Aquatic Masterpiece
        '''
        '''Weaving a tapestry of artistry, surrealism and theatrical romance, &apos;O&apos; 
        '''pays tribute to the beauty of theatre. Inspired by the concept of infinity 
        '''and the elegance of water, world-class acrobats, synchronized swimmers 
        '''and divers create a breathtaking experience..
        '''</summary>
        Friend ReadOnly Property String6() As String
            Get
                Return ResourceManager.GetString("String6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In a New Light
        '''
        '''Beloved by fans around the world, iconic Alegría is reinterpreted in a 
        '''renewed version to share  its timeless  story  once more. The  classic 
        '''power struggle of old meets new is reinterpreted for today’s cultural pulse. 
        '''Led by an intangible wind of change, an emerging movement strives to 
        '''shake the established order, instilling hope and renewal to bring light to 
        '''a world in perfect harmony. Alegría energizes the audience with a joyful 
        '''spirit for a brighter and more inspiring tomor [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property String7() As String
            Get
                Return ResourceManager.GetString("String7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A  storm that  defies even  the
        '''stoutest seafaring heart. Cruel 
        '''seas, battle-hardened sailors, 
        '''wave-tossed ships. The safety 
        '''of the shore seems far, far away..
        '''</summary>
        Friend ReadOnly Property String8() As String
            Get
                Return ResourceManager.GetString("String8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A never-before imagined stage, 
        '''the steepest challenge faced on
        '''the  journey.  Expert  warriors  in 
        '''mortal combat on a dimension-
        '''defying   battlefield.   When  the 
        '''earth becomes  the  sky,  only the
        '''truly courageous can prevail..
        '''</summary>
        Friend ReadOnly Property String9() As String
            Get
                Return ResourceManager.GetString("String9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wallpaper() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wallpaper", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
